### ISSUE TITLE
Themeing

### ISSUE THREAD

**Issue by poirazis** [melohagan/budibase-component-number-counter-input#1]
Hey @melohagan and thanks for the nice component ! 
Wanted to report that it doesnt seem to be following the selected theme though 
![Screenshot 2023-06-28 at 6 19 55 PM](https://github.com/melohagan/budibase-component-number-counter-input/assets/80512170/c6fd2051-939f-4edc-b32a-b838a136724d)

**Comment by melohagan** [comment]
Good catch, cheers!

I'll take a look if I happen to get chance :)

**Comment by melohagan** [comment]
Hey @poirazis 

I've had a bit of a look at this one, and I think the best I can do at the moment is determine if the theme is dark and set the SvelteUIProvider colorScheme to "dark".
I believe I'll need this to be implemented though: https://github.com/Budibase/budibase/issues/11409

Although you probably know better than me if there's a way in a custom component to get the theme?

Played around with a few things in the SvelteUI docs but wasn't having much luck.

**Comment by poirazis** [comment]
Hey @melohagan 
currently , i lookup which theme is active by looking at the classes of the "spectrum-root"  DIV !

 
<img width="1011" alt="Screenshot 2023-08-16 at 3 04 27 PM" src="https://github.com/melohagan/budibase-component-number-counter-input/assets/80512170/96be6d4c-89e8-4070-9271-88cda0bf08d3">

**Comment by melohagan** [comment]
Cheers @poirazis ! It might be a little hacky to read the DOM tree like that, but could be worth it as a quick fix.

**Comment by poirazis** [comment]
I would suggest each screen has a Theme property ( to be able to override the application wide setting per screen ) and that property should be exposed as a binding to conditionally react depending on which Theme is active.

But for the time being, i didnt find another way to quickly grab the active theme
